# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            # https://symfony.com/doc/current/reference/configuration/security.html#firewall-context
            context:            staff
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /admin
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true

        # -> end custom configuration

        # default login area for standard users
        main:
            pattern:             .*
            context:             user
            provider: symfony_security_firwall_user_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                use_referer: true
                require_previous_session: false
            logout:
                path: logout
                target: login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    role_hierarchy:
        ROLE_STAFF:       [ROLE_USER]
        ROLE_ADMIN:       [ROLE_SONATA_ADMIN, ROLE_STAFF]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Service\SymfonySecurityFirewallUser: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        symfony_security_firwall_user_provider:
            id: user.symfony_security_firwall_user_provider

    acl:
        connection: default

    access_decision_manager:
        strategy: unanimous

    access_control:
        # Admin login page needs to be accessed without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_USER, ROLE_STAFF] }
        - { path: ^/user/.*, role: ROLE_USER }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

